apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sales-system
data:
  db_host_port: "database-service.sales-system.svc.cluster.local:5432"
  db_user: "postgres"
  db_password: "postgres"
  db_disable_tls: "true"