apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
# Persistence storage own by the cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: sales-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-data
        - name: config
          configMap:
            name: pghbaconf
              # defaultMode: 0400
            items:
              - key: "pg_hba.conf"
                path: "pg_hba.conf"
      containers:
        - name: postgres
          image: postgres:17.5
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - mountPath: "/etc/pg_hba.conf"
              name: config
              readOnly: false
              subPath: "pg_hba.conf"
          args: ["-c", "hba_file=/etc/pg_hba.conf"]
          resources:
            requests:
              # Always available on the Node
              # Using 10% of the CPU capacity
              cpu: 100m
            limits:
              # Using 3 and a half of the CPU
              # The rest of the services will fight for the 3500
              cpu: 3500m
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
          livenessProbe:
            exec:
              command: [ "pg_isready", "-h", "localhost", "-U", "postgres" ]
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 5432
      name: postgres
      targetPort: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pghbaconf
  namespace: sales-system
data:
  # file-like keys
  pg_hba.conf: |
    local   all             all                                     trust
    # IPv4 local connections:
    host    all             all             0.0.0.0/0               trust
    # IPv6 local connections (allow all IPv6 for Kind network access):
    host    all             all             ::/0                    trust
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     trust
    host    replication     all             0.0.0.0/0               trust
    host    replication     all             ::/0                    trust


